name: animals_task
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  connectivity_plus: ^6.1.5
  flutter_screenutil: ^5.9.3
  flutter_bloc: ^8.1.1
  flutter_spinkit: ^5.2.1
  fluttertoast: ^8.2.12
  pinput: ^5.0.1
  dio: ^5.1.1
  pretty_dio_logger: ^1.3.1
  get_it: ^7.6.0
  shared_preferences: ^2.3.2 
  path_provider: ^2.1.5
  flutter_svg: ^2.0.17 
  google_fonts: ^6.2.1
  dropdown_button2: ^2.3.9
  flutter_secure_storage: ^9.2.4
  json_serializable: ^6.8.0
  build_runner: ^2.3.3
  json_annotation: ^4.9.0
  freezed_annotation: ^2.2.0
  freezed: ^2.5.2
  retrofit: ^4.4.1
  retrofit_generator: 
  gap: ^3.0.1
  flutter_animate: ^4.5.2
  loading_animation_widget: ^1.3.0
  flutter_lints: ^5.0.0
  bloc_test: ^9.1.5
  mockito: ^5.4.4
  equatable: ^2.0.7




dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter


flutter:
  uses-material-design: true
  assets:
    - assets/images/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

